import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedsignoutoverlaywidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedsignoutoverlaywidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedsignoutoverlaywidget/generated/GeneratedJuniorStaffPengembanganTeknologiInformasiWidget17.dart';
import 'package:flutterapp/pelni_oneapp/generatedsignoutoverlaywidget/generated/GeneratedApakahandayakinuntukkeluarWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedsignoutoverlaywidget/generated/GeneratedBrianMayMilwaukeeWidget1.dart';
import 'package:flutterapp/pelni_oneapp/generatedsignoutoverlaywidget/generated/GeneratedKeluarWidget2.dart';
import 'package:flutterapp/pelni_oneapp/generatedsignoutoverlaywidget/generated/GeneratedEllipse2Widget.dart';

/* Frame Sign Out Overlay
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignOutOverlayWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(15.0),
      child: Container(
        width: 334.0,
        height: 268.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(15.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(15.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 110.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 115.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 21.0,
                child: GeneratedBrianMayMilwaukeeWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 15.0,
                child:
                    GeneratedJuniorStaffPengembanganTeknologiInformasiWidget17(),
              ),
              Positioned(
                left: 23.0,
                top: 232.5,
                right: null,
                bottom: null,
                width: 287.01568603515625,
                height: 2.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 128.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 106.10526275634766,
                height: 24.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 136.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 24.0,
                child: GeneratedKeluarWidget2(),
              ),
              Positioned(
                left: 75.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 186.0,
                height: 15.0,
                child: GeneratedApakahandayakinuntukkeluarWidget(),
              )
            ]),
      ),
    ));
  }
}
