import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedGolf_courseWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedHot_tubWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedRv_hookupWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedAc_unitWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedHeaderWidget17.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedCasinoWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedRoom_serviceWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedSmoke_freeWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedBusiness_centerWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedBeach_accessWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedChild_careWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedKitchenWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedPoolWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedChild_friendlyWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedFitness_centerWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedAirport_shuttleWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedFree_breakfastWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedSpaWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedSmoking_roomsWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceswidget/generated/GeneratedAll_inclusiveWidget.dart';

/* Frame Icons — Places
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconsPlacesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 392.0,
        height: 176.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAc_unitWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAirport_shuttleWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAll_inclusiveWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBeach_accessWidget(),
              ),
              Positioned(
                left: 184.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBusiness_centerWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCasinoWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChild_careWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChild_friendlyWidget(),
              ),
              Positioned(
                left: 344.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFitness_centerWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFree_breakfastWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGolf_courseWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedHot_tubWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedKitchenWidget(),
              ),
              Positioned(
                left: 184.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPoolWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRoom_serviceWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRv_hookupWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSmoke_freeWidget(),
              ),
              Positioned(
                left: 344.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSmoking_roomsWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSpaWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 32.0,
                child: GeneratedHeaderWidget17(),
              )
            ]),
      ),
    ));
  }
}
