import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniconferencewidget/generated/GeneratedGroup40Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniconferencewidget/generated/GeneratedNavBarWidget1.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniconferencewidget/generated/GeneratedGroup39Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniconferencewidget/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniconferencewidget/generated/GeneratedGroup37Widget1.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniconferencewidget/generated/GeneratedIOSLargeWidget8.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniconferencewidget/generated/GeneratedNavigate_beforeWidget8.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniconferencewidget/generated/GeneratedInfo_outlineWidget8.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniconferencewidget/generated/GeneratedProfileWidget3.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniconferencewidget/generated/GeneratedGroup38Widget.dart';

/* Frame Pelni Conference
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPelniConferenceWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 85.0,
                child: GeneratedRectangle7Widget2(),
              ),
              Positioned(
                left: -16.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 44.0,
                child: GeneratedIOSLargeWidget8(),
              ),
              Positioned(
                left: 8.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNavigate_beforeWidget8(),
              ),
              Positioned(
                left: 78.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 27.0,
                child: GeneratedProfileWidget3(),
              ),
              Positioned(
                left: 341.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedInfo_outlineWidget8(),
              ),
              Positioned(
                left: 3.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 83.0,
                child: GeneratedNavBarWidget1(),
              ),
              Positioned(
                left: 26.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 36.0,
                child: GeneratedGroup37Widget1(),
              ),
              Positioned(
                left: 9.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 160.0,
                child: GeneratedGroup38Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 160.0,
                child: GeneratedGroup39Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 160.0,
                child: GeneratedGroup40Widget(),
              )
            ]),
      ),
    ));
  }
}
