import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedhome_screenwidget/generated/GeneratedFrameDashboardWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedhome_screenwidget/generated/GeneratedTop_home_screen1Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedhome_screenwidget/generated/GeneratedIOSLargeWidget18.dart';
import 'package:flutterapp/pelni_oneapp/generatedhome_screenwidget/generated/GeneratedKeluarWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedhome_screenwidget/generated/GeneratedDashboardWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedhome_screenwidget/generated/Generated9999Widget8.dart';
import 'package:flutterapp/pelni_oneapp/generatedhome_screenwidget/generated/GeneratedBrianMayMilwaukeeWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedhome_screenwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedhome_screenwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedhome_screenwidget/generated/GeneratedPengembanganTeknologiInformasiWidget1.dart';
import 'package:flutterapp/pelni_oneapp/generatedhome_screenwidget/generated/GeneratedJuniorStaffPengembanganTeknologiInformasiWidget16.dart';

/* Frame Home_Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome_ScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 230, 241, 241),
                ),
              ),
              Positioned(
                left: 160.5137939453125,
                top: 70.45870971679688,
                right: null,
                bottom: null,
                width: 133.81651306152344,
                height: 85.18443298339844,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: -6.0,
                top: -2.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 297.0,
                child: GeneratedTop_home_screen1Widget(),
              ),
              Positioned(
                left: -16.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 44.0,
                child: GeneratedIOSLargeWidget18(),
              ),
              Positioned(
                left: 21.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 124.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 165.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 21.0,
                child: GeneratedBrianMayMilwaukeeWidget(),
              ),
              Positioned(
                left: 165.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 28.0,
                child:
                    GeneratedJuniorStaffPengembanganTeknologiInformasiWidget16(),
              ),
              Positioned(
                left: 165.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 28.0,
                child: GeneratedPengembanganTeknologiInformasiWidget1(),
              ),
              Positioned(
                left: 165.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 21.0,
                child: Generated9999Widget8(),
              ),
              Positioned(
                left: 21.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 30.0,
                child: GeneratedDashboardWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 493.0,
                child: GeneratedFrameDashboardWidget(),
              ),
              Positioned(
                left: 333.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedKeluarWidget(),
              )
            ]),
      ),
    ));
  }
}
