import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/GeneratedABSENWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/Generated0800Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/GeneratedInfo_outlineWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/GeneratedProfileWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/GeneratedNavigate_beforeWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/GeneratedNewNormallifePTPELNIPerseroCovidSafeBUMNWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/GeneratedPageabsen1Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/GeneratedIOSLargeWidget2.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/GeneratedSenin01Januari2020Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/GeneratedSelamatdatangBrianSilahkanCheckinCheckOutsebelumandaMas.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensiwidget/generated/GeneratedAssets_pelni_PelniOne11Widget2.dart';

/* Frame Pelni Absensi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPelniAbsensiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 142.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 54.0,
                child: GeneratedAssets_pelni_PelniOne11Widget2(),
              ),
              Positioned(
                left: -16.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 44.0,
                child: GeneratedIOSLargeWidget2(),
              ),
              Positioned(
                left: 8.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNavigate_beforeWidget(),
              ),
              Positioned(
                left: 149.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 30.0,
                child: GeneratedProfileWidget(),
              ),
              Positioned(
                left: 341.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedInfo_outlineWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 457.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 77.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 53.0,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 137.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 34.0,
                child: GeneratedABSENWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 282.0,
                child: GeneratedPageabsen1Widget(),
              ),
              Positioned(
                left: 111.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 74.0,
                child: Generated0800Widget(),
              ),
              Positioned(
                left: 84.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 25.0,
                child: GeneratedSenin01Januari2020Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 44.0,
                child:
                    GeneratedSelamatdatangBrianSilahkanCheckinCheckOutsebelumandaMas(),
              ),
              Positioned(
                left: 28.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 16.0,
                child:
                    GeneratedNewNormallifePTPELNIPerseroCovidSafeBUMNWidget(),
              )
            ]),
      ),
    ));
  }
}
