import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofilewidget/generated/GeneratedFrame9Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofilewidget/generated/GeneratedProfileWidget2.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofilewidget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofilewidget/generated/GeneratedNavigate_beforeWidget6.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofilewidget/generated/GeneratedIOSLargeWidget7.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofilewidget/generated/GeneratedInfo_outlineWidget6.dart';

/* Frame Pelni Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPelniProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 85.0,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: -16.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 44.0,
                child: GeneratedIOSLargeWidget7(),
              ),
              Positioned(
                left: 8.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNavigate_beforeWidget6(),
              ),
              Positioned(
                left: 161.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 30.0,
                child: GeneratedProfileWidget2(),
              ),
              Positioned(
                left: 341.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedInfo_outlineWidget6(),
              ),
              Positioned(
                left: 9.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 702.0,
                child: GeneratedFrame9Widget(),
              )
            ]),
      ),
    ));
  }
}
