import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedNRPWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedLine19Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedLine16Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedIOSLargeWidget10.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedPengembanganTeknologiInformasiWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedNamaWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedInfo_outlineWidget12.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedNavigate_beforeWidget12.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedProfileWidget5.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedTanggalMasukWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedJabatanGradeWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedJuniorStaffPengembanganTeknologiInformasiWidget15.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedLine17Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedLine18Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedAlexanderPiercepelnicoidWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedUnitKerjaWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedRectangle7Widget4.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/Generated1Januari2001Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/Generated9999Widget7.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedAlexanderPierceMilwaukeeWidget7.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniprofiledetailwidget/generated/GeneratedLine20Widget.dart';

/* Frame Pelni Profile (Detail)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPelniProfileDetailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 85.0,
                child: GeneratedRectangle7Widget4(),
              ),
              Positioned(
                left: -16.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 44.0,
                child: GeneratedIOSLargeWidget10(),
              ),
              Positioned(
                left: 8.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNavigate_beforeWidget12(),
              ),
              Positioned(
                left: 161.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 30.0,
                child: GeneratedProfileWidget5(),
              ),
              Positioned(
                left: 341.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedInfo_outlineWidget12(),
              ),
              Positioned(
                left: 112.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 151.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 19.0,
                child: GeneratedNamaWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 22.0,
                child: GeneratedAlexanderPierceMilwaukeeWidget7(),
              ),
              Positioned(
                left: 42.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 22.0,
                child: GeneratedNRPWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 309.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 25.0,
                child: Generated9999Widget7(),
              ),
              Positioned(
                left: 40.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 1.0,
                child: GeneratedLine16Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 22.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 25.0,
                child: GeneratedAlexanderPiercepelnicoidWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 1.0,
                child: GeneratedLine17Widget(),
              ),
              Positioned(
                left: 45.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 19.0,
                child: GeneratedUnitKerjaWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 22.0,
                child: GeneratedPengembanganTeknologiInformasiWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 1.0,
                child: GeneratedLine18Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 19.0,
                child: GeneratedJabatanGradeWidget(),
              ),
              Positioned(
                left: 60.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 40.0,
                child:
                    GeneratedJuniorStaffPengembanganTeknologiInformasiWidget15(),
              ),
              Positioned(
                left: 47.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 1.0,
                child: GeneratedLine19Widget(),
              ),
              Positioned(
                left: 45.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 19.0,
                child: GeneratedTanggalMasukWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 21.0,
                child: Generated1Januari2001Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 1.0,
                child: GeneratedLine20Widget(),
              )
            ]),
      ),
    ));
  }
}
