import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnislipgajiwidget/generated/GeneratedGroup37Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnislipgajiwidget/generated/GeneratedGroup42Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnislipgajiwidget/generated/GeneratedFrame11Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnislipgajiwidget/generated/GeneratedInfo_outlineWidget2.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnislipgajiwidget/generated/GeneratedIOSLargeWidget3.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnislipgajiwidget/generated/GeneratedAssets_pelni_PelniOne11Widget3.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnislipgajiwidget/generated/GeneratedProfileWidget1.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnislipgajiwidget/generated/GeneratedNavigate_beforeWidget2.dart';

/* Frame Pelni Slip Gaji
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPelniSlipGajiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 142.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 54.0,
                child: GeneratedAssets_pelni_PelniOne11Widget3(),
              ),
              Positioned(
                left: -16.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 44.0,
                child: GeneratedIOSLargeWidget3(),
              ),
              Positioned(
                left: 8.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNavigate_beforeWidget2(),
              ),
              Positioned(
                left: 147.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 27.0,
                child: GeneratedProfileWidget1(),
              ),
              Positioned(
                left: 341.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedInfo_outlineWidget2(),
              ),
              Positioned(
                left: 26.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 36.0,
                child: GeneratedGroup37Widget(),
              ),
              Positioned(
                left: 265.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 26.729412078857422,
                child: GeneratedGroup42Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 619.0,
                child: GeneratedFrame11Widget(),
              )
            ]),
      ),
    ));
  }
}
