import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedAppsWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedCancelWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedSubdirectory_arrow_leftWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedMore_vertWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedFirst_pageWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedChevron_leftWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedFullscreen_exitWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedExpand_lessWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedArrow_drop_downWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedArrow_drop_down_circleWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedChevron_rightWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedFullscreenWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedCloseWidget8.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedExpand_moreWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedSubdirectory_arrow_rightWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedHeaderWidget16.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedArrow_backWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedLast_pageWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedCheckWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedArrow_drop_upWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedArrow_downwardWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedRefreshWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedArrow_forwardWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedMenuWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedMore_horizWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsnavigationwidget/generated/GeneratedArrow_upwardWidget.dart';

/* Frame Icons — Navigation
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconsNavigationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 392.0,
        height: 176.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAppsWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrow_backWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrow_downwardWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrow_drop_downWidget(),
              ),
              Positioned(
                left: 184.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrow_drop_down_circleWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrow_drop_upWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrow_forwardWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrow_upwardWidget(),
              ),
              Positioned(
                left: 344.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCancelWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCheckWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChevron_leftWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedChevron_rightWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCloseWidget8(),
              ),
              Positioned(
                left: 184.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedExpand_lessWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedExpand_moreWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFirst_pageWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFullscreenWidget(),
              ),
              Positioned(
                left: 344.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFullscreen_exitWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedLast_pageWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMenuWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMore_horizWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMore_vertWidget(),
              ),
              Positioned(
                left: 184.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRefreshWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSubdirectory_arrow_leftWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSubdirectory_arrow_rightWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 32.0,
                child: GeneratedHeaderWidget16(),
              )
            ]),
      ),
    ));
  }
}
