import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnirekamanconferencewidget/generated/GeneratedInfo_outlineWidget10.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnirekamanconferencewidget/generated/GeneratedNavigate_beforeWidget10.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnirekamanconferencewidget/generated/GeneratedGroup37Widget2.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnirekamanconferencewidget/generated/GeneratedFrame10Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnirekamanconferencewidget/generated/GeneratedIOSLargeWidget9.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnirekamanconferencewidget/generated/GeneratedProfileWidget4.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnirekamanconferencewidget/generated/GeneratedNavBarWidget2.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnirekamanconferencewidget/generated/GeneratedRectangle7Widget3.dart';

/* Frame Pelni Rekaman Conference 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPelniRekamanConferenceWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 85.0,
                child: GeneratedRectangle7Widget3(),
              ),
              Positioned(
                left: -16.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 44.0,
                child: GeneratedIOSLargeWidget9(),
              ),
              Positioned(
                left: 8.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNavigate_beforeWidget10(),
              ),
              Positioned(
                left: 83.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 27.0,
                child: GeneratedProfileWidget4(),
              ),
              Positioned(
                left: 341.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedInfo_outlineWidget10(),
              ),
              Positioned(
                left: 3.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 83.0,
                child: GeneratedNavBarWidget2(),
              ),
              Positioned(
                left: 26.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 36.0,
                child: GeneratedGroup37Widget2(),
              ),
              Positioned(
                left: 9.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 568.0,
                child: GeneratedFrame10Widget(),
              )
            ]),
      ),
    ));
  }
}
