import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniscanqrcodewidget/generated/GeneratedAssets_pelni_PelniOne11Widget4.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniscanqrcodewidget/generated/GeneratedIOSLargeWidget4.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniscanqrcodewidget/generated/GeneratedSwitch_cameraWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniscanqrcodewidget/generated/GeneratedClearWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniscanqrcodewidget/generated/GeneratedRectangle27Widget.dart';

/* Frame Pelni Scan Qr Code
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPelniScanQrCodeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 142.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 54.0,
                child: GeneratedAssets_pelni_PelniOne11Widget4(),
              ),
              Positioned(
                left: -16.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 44.0,
                child: GeneratedIOSLargeWidget4(),
              ),
              Positioned(
                left: 38.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 300.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedClearWidget(),
              ),
              Positioned(
                left: 321.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedSwitch_cameraWidget(),
              )
            ]),
      ),
    ));
  }
}
