import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget2/generated/GeneratedDriveWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget2/generated/GeneratedHangoutsWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget2/generated/GeneratedBluetoothWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget2/generated/GeneratedGoogleWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget2/generated/GeneratedHeaderWidget5.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget2/generated/GeneratedGmailWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget2/generated/GeneratedKeepWidget.dart';

/* Frame Icons — Placeholder
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconsPlaceholderWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 392.0,
        height: 200.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 32.0,
                child: GeneratedHeaderWidget5(),
              ),
              Positioned(
                left: 52.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedGmailWidget(),
              ),
              Positioned(
                left: 132.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedHangoutsWidget(),
              ),
              Positioned(
                left: 212.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedGoogleWidget(),
              ),
              Positioned(
                left: 292.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedDriveWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedKeepWidget(),
              ),
              Positioned(
                left: 132.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedBluetoothWidget(),
              )
            ]),
      ),
    ));
  }
}
