import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreenkotakkeluarwidget/generated/GeneratedIOSLargeWidget11.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreenkotakkeluarwidget/generated/GeneratedNavBarWidget3.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreenkotakkeluarwidget/generated/GeneratedDokumenFileWidget1.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreenkotakkeluarwidget/generated/GeneratedNavigate_beforeWidget14.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreenkotakkeluarwidget/generated/GeneratedRectangle7Widget5.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreenkotakkeluarwidget/generated/GeneratedPelniDocWidget1.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreenkotakkeluarwidget/generated/GeneratedInfo_outlineWidget14.dart';

/* Frame Pelni Doc Screen (Kotak Keluar)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPelniDocScreenKotakKeluarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 85.0,
                child: GeneratedRectangle7Widget5(),
              ),
              Positioned(
                left: -16.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 44.0,
                child: GeneratedIOSLargeWidget11(),
              ),
              Positioned(
                left: 8.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNavigate_beforeWidget14(),
              ),
              Positioned(
                left: 143.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 26.0,
                child: GeneratedPelniDocWidget1(),
              ),
              Positioned(
                left: 341.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedInfo_outlineWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 651.0,
                child: GeneratedDokumenFileWidget1(),
              ),
              Positioned(
                left: 3.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 76.0,
                child: GeneratedNavBarWidget3(),
              )
            ]),
      ),
    ));
  }
}
