import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsalertwidget/generated/GeneratedAdd_alertWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsalertwidget/generated/GeneratedErrorWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsalertwidget/generated/GeneratedWarningWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsalertwidget/generated/GeneratedError_outlineWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsalertwidget/generated/GeneratedHeaderWidget1.dart';

/* Frame Icons — Alert
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconsAlertWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 392.0,
        height: 96.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 23.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAdd_alertWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedErrorWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedError_outlineWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedWarningWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 32.0,
                child: GeneratedHeaderWidget1(),
              )
            ]),
      ),
    ));
  }
}
