import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedBlockWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedFlagWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedUndoWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedText_formatWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedFont_downloadWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedAdd_circle_outlineWidget8.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedSelect_allWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedInboxWidget9.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedSaveWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedArchiveWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedRemove_circle_outlineWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedClearWidget4.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedWeekendWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedSortWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedRedoWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedContent_pasteWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedSendWidget8.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedReportWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedUnarchiveWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedRemove_circleWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedDraftsWidget8.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedContent_cutWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedLinkWidget2.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedRemoveWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedAdd_circleWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedCreateWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedFilter_listWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedAddWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedNext_weekWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedMailWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedGestureWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedReply_allWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedMarkunreadWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedReplyWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedDelete_sweepWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedLinkWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedBackspaceWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedHeaderWidget7.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedMove_to_inboxWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedForwardWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedAdd_boxWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconscontentwidget/generated/GeneratedContent_copyWidget.dart';

/* Frame Icons — Content
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconsContentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 392.0,
        height: 256.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAddWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAdd_boxWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAdd_circleWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAdd_circle_outlineWidget8(),
              ),
              Positioned(
                left: 184.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArchiveWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBackspaceWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBlockWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedClearWidget4(),
              ),
              Positioned(
                left: 344.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedContent_copyWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedContent_cutWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedContent_pasteWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCreateWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedDelete_sweepWidget(),
              ),
              Positioned(
                left: 184.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedDraftsWidget8(),
              ),
              Positioned(
                left: 224.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFilter_listWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFlagWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFont_downloadWidget(),
              ),
              Positioned(
                left: 344.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedForwardWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGestureWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedInboxWidget9(),
              ),
              Positioned(
                left: 104.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedLinkWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedLinkWidget2(),
              ),
              Positioned(
                left: 184.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMailWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMarkunreadWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMove_to_inboxWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNext_weekWidget(),
              ),
              Positioned(
                left: 344.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRedoWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRemoveWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRemove_circleWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRemove_circle_outlineWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedReplyWidget(),
              ),
              Positioned(
                left: 184.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedReply_allWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedReportWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSaveWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSelect_allWidget(),
              ),
              Positioned(
                left: 344.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSendWidget8(),
              ),
              Positioned(
                left: 24.0,
                top: 208.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSortWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 208.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedText_formatWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 208.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedUnarchiveWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 208.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedUndoWidget(),
              ),
              Positioned(
                left: 184.0,
                top: 208.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedWeekendWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 32.0,
                child: GeneratedHeaderWidget7(),
              )
            ]),
      ),
    ));
  }
}
