import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatediconstogglewidget/generated/GeneratedCheck_boxWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconstogglewidget/generated/GeneratedIndeterminate_check_boxWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconstogglewidget/generated/GeneratedHeaderWidget3.dart';
import 'package:flutterapp/pelni_oneapp/generatediconstogglewidget/generated/GeneratedStar_halfWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconstogglewidget/generated/GeneratedRadio_button_checkedWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconstogglewidget/generated/GeneratedRadio_button_uncheckedWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconstogglewidget/generated/GeneratedStar_borderWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconstogglewidget/generated/GeneratedStarWidget2.dart';
import 'package:flutterapp/pelni_oneapp/generatediconstogglewidget/generated/GeneratedCheck_box_outline_blankWidget.dart';

/* Frame Icons — Toggle
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconsToggleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 392.0,
        height: 96.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCheck_boxWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCheck_box_outline_blankWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIndeterminate_check_boxWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRadio_button_checkedWidget(),
              ),
              Positioned(
                left: 184.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRadio_button_uncheckedWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedStarWidget2(),
              ),
              Positioned(
                left: 264.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedStar_borderWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedStar_halfWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 32.0,
                child: GeneratedHeaderWidget3(),
              )
            ]),
      ),
    ));
  }
}
