import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generateddetailslipgajiwidget/generated/GeneratedRectangle11Widget3.dart';
import 'package:flutterapp/pelni_oneapp/generateddetailslipgajiwidget/generated/GeneratedSlipGajiJanuari2020Widget.dart';
import 'package:flutterapp/pelni_oneapp/generateddetailslipgajiwidget/generated/GeneratedCloseWidget6.dart';
import 'package:flutterapp/pelni_oneapp/generateddetailslipgajiwidget/generated/GeneratedFrame2Widget4.dart';
import 'package:flutterapp/pelni_oneapp/generateddetailslipgajiwidget/generated/GeneratedAdd_circle_outlineWidget6.dart';

/* Frame Detail Slip Gaji
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailSlipGajiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(15.0),
      child: Container(
        width: 375.0,
        height: 778.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(15.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(15.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 63.0,
                child: GeneratedRectangle11Widget3(),
              ),
              Positioned(
                left: 96.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 24.0,
                child: GeneratedSlipGajiJanuari2020Widget(),
              ),
              Positioned(
                left: 157.0,
                top: -93.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCloseWidget6(),
              ),
              Positioned(
                left: 343.9167175292969,
                top: 16.06404685974121,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAdd_circle_outlineWidget6(),
              ),
              Positioned(
                left: 4.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 368.0,
                height: 520.0,
                child: GeneratedFrame2Widget4(),
              )
            ]),
      ),
    ));
  }
}
