import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreendetaildocwidget/generated/GeneratedAssignmentWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreendetaildocwidget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreendetaildocwidget/generated/GeneratedRectangle7Widget7.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreendetaildocwidget/generated/GeneratedNavigate_beforeWidget18.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreendetaildocwidget/generated/GeneratedGroup23Widget1.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreendetaildocwidget/generated/GeneratedIOSLargeWidget13.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreendetaildocwidget/generated/GeneratedPelniDocWidget3.dart';

/* Frame Pelni Doc Screen (Detail Doc)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPelniDocScreenDetailDocWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 85.0,
                  child: GeneratedRectangle7Widget7(),
                ),
                Positioned(
                  left: -16.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 396.0,
                  height: 44.0,
                  child: GeneratedIOSLargeWidget13(),
                ),
                Positioned(
                  left: 8.0,
                  top: 50.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedNavigate_beforeWidget18(),
                ),
                Positioned(
                  left: 143.0,
                  top: 50.0,
                  right: null,
                  bottom: null,
                  width: 91.0,
                  height: 26.0,
                  child: GeneratedPelniDocWidget3(),
                ),
                Positioned(
                  left: 341.0,
                  top: 50.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedAssignmentWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 750.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 62.0,
                  child: GeneratedGroup23Widget1(),
                ),
                Positioned(
                  left: -2.0,
                  top: 96.0,
                  right: null,
                  bottom: null,
                  width: 368.0,
                  height: 665.0,
                  child: GeneratedFrame2Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
