import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedFolder_openWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedFile_uploadWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedCloudWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedCloud_doneWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedCloud_queueWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedCloud_downloadWidget12.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedFolderWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedFolder_sharedWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedCreate_new_folderWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedCloud_uploadWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedAttachmentWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedCloud_offWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedHeaderWidget2.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedCloud_circleWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsfilewidget/generated/GeneratedFile_downloadWidget16.dart';

/* Frame Icons — File
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconsFileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 392.0,
        height: 136.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 23.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAttachmentWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCloudWidget(),
              ),
              Positioned(
                left: 103.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCloud_circleWidget(),
              ),
              Positioned(
                left: 143.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCloud_doneWidget(),
              ),
              Positioned(
                left: 183.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCloud_downloadWidget12(),
              ),
              Positioned(
                left: 223.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCloud_offWidget(),
              ),
              Positioned(
                left: 263.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCloud_queueWidget(),
              ),
              Positioned(
                left: 303.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCloud_uploadWidget(),
              ),
              Positioned(
                left: 343.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCreate_new_folderWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFile_downloadWidget16(),
              ),
              Positioned(
                left: 63.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFile_uploadWidget(),
              ),
              Positioned(
                left: 102.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFolderWidget(),
              ),
              Positioned(
                left: 142.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFolder_openWidget(),
              ),
              Positioned(
                left: 183.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFolder_sharedWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 32.0,
                child: GeneratedHeaderWidget2(),
              )
            ]),
      ),
    ));
  }
}
