import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedgroupwidget17/generated/GeneratedSwatchesRedWidget17.dart';

/* Group Group
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroupWidget17 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 462.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 462.0,
              child: GeneratedSwatchesRedWidget17(),
            )
          ]),
    ));
  }
}
