import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreendetaildocwidget1/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreendetaildocwidget1/generated/GeneratedKomitmenBersamaatasPenyelenggaraanKewajibanPelayaranPub.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreendetaildocwidget1/generated/GeneratedIOSLargeWidget14.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreendetaildocwidget1/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelnidocscreendetaildocwidget1/generated/GeneratedFrame8Widget.dart';

/* Frame Pelni Doc Screen (Detail Doc)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPelniDocScreenDetailDocWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -50.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 425.0,
                height: 128.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 85.0,
                child: GeneratedGroup28Widget(),
              ),
              Positioned(
                left: -16.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 44.0,
                child: GeneratedIOSLargeWidget14(),
              ),
              Positioned(
                left: 7.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 364.0,
                height: 53.0,
                child:
                    GeneratedKomitmenBersamaatasPenyelenggaraanKewajibanPelayaranPub(),
              ),
              Positioned(
                left: 7.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 618.0,
                child: GeneratedFrame8Widget(),
              )
            ]),
      ),
    ));
  }
}
