import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedNotifications_noneWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedWhatshotWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedGroup_addWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedPeople_outlineWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedNotifications_pausedWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedNotifications_activeWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedMoodWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedPollWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedDomainWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedSentiment_very_satisfiedWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedSentiment_satisfiedWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedLocation_cityWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedNotifications_offWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedPersonWidget2.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedHeaderWidget8.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedMood_badWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedSchoolWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedPerson_outlineWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedSentiment_neutralWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedPlus_oneWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedPublicWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedShareWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedPagesWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedSentiment_dissatisfiedWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedParty_modeWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedCakeWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedPeopleWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedPerson_addWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedNotificationsWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedSentiment_very_dissatisfiedWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconssocialwidget/generated/GeneratedGroupWidget48.dart';

/* Frame Icons — Social
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconsSocialWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 392.0,
        height: 216.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCakeWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedDomainWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGroupWidget48(),
              ),
              Positioned(
                left: 144.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedGroup_addWidget(),
              ),
              Positioned(
                left: 184.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedLocation_cityWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMoodWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMood_badWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNotificationsWidget(),
              ),
              Positioned(
                left: 344.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNotifications_activeWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNotifications_noneWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNotifications_offWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNotifications_pausedWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPagesWidget(),
              ),
              Positioned(
                left: 184.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedParty_modeWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPeopleWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPeople_outlineWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPersonWidget2(),
              ),
              Positioned(
                left: 344.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPerson_addWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPerson_outlineWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPlus_oneWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPollWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPublicWidget(),
              ),
              Positioned(
                left: 184.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSchoolWidget(),
              ),
              Positioned(
                left: 223.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSentiment_dissatisfiedWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSentiment_neutralWidget(),
              ),
              Positioned(
                left: 304.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSentiment_satisfiedWidget(),
              ),
              Positioned(
                left: 344.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSentiment_very_dissatisfiedWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedSentiment_very_satisfiedWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedShareWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedWhatshotWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 32.0,
                child: GeneratedHeaderWidget8(),
              )
            ]),
      ),
    ));
  }
}
