import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedMasukanUsernameAndaWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedPersonWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedHttpsWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedMain_bottom1Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedMasukanPasswordAndaWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedPagelogin1Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedMain_bottom2Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedAssets_pelni_PelniOne12Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedIOSLargeWidget17.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedVersionBETAWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedSignInWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedLogin_bottom1Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedloginpagewidget/generated/GeneratedLoginWidget.dart';

/* Frame Login Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -13.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 401.0,
                height: 301.0,
                child: GeneratedPagelogin1Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 87.0,
                child: GeneratedAssets_pelni_PelniOne12Widget(),
              ),
              Positioned(
                left: 218.0,
                top: 679.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 157.0,
                child: GeneratedLogin_bottom1Widget(),
              ),
              Positioned(
                left: -36.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 222.0,
                child: GeneratedMain_bottom1Widget(),
              ),
              Positioned(
                left: 114.00000762939453,
                top: 0.000009703929208626505,
                right: null,
                bottom: null,
                width: 150.0,
                height: 222.0,
                child: GeneratedMain_bottom2Widget(),
              ),
              Positioned(
                left: 154.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 27.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 59.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 59.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 69.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 54.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 135.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 36.0,
                child: GeneratedSignInWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPersonWidget(),
              ),
              Positioned(
                left: 105.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 22.0,
                child: GeneratedMasukanUsernameAndaWidget(),
              ),
              Positioned(
                left: 105.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 22.0,
                child: GeneratedMasukanPasswordAndaWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedHttpsWidget(),
              ),
              Positioned(
                left: 152.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 14.0,
                child: GeneratedVersionBETAWidget(),
              ),
              Positioned(
                left: -16.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 44.0,
                child: GeneratedIOSLargeWidget17(),
              )
            ]),
      ),
    ));
  }
}
