import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget/generated/Generated40pxWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget/generated/GeneratedHeaderWidget4.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget/generated/Generated24pxWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget/generated/Generated36pxWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget/generated/Generated48pxWidget.dart';
import 'package:flutterapp/pelni_oneapp/generatediconsplaceholderwidget/generated/Generated18pxWidget.dart';

/* Frame Icons — Placeholder
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconsPlaceholderWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 392.0,
        height: 120.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 32.0,
                child: GeneratedHeaderWidget4(),
              ),
              Positioned(
                left: 58.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: Generated24pxWidget(),
              ),
              Positioned(
                left: 150.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: Generated40pxWidget(),
              ),
              Positioned(
                left: 98.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: Generated36pxWidget(),
              ),
              Positioned(
                left: 206.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: Generated48pxWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 18.0,
                child: Generated18pxWidget(),
              )
            ]),
      ),
    ));
  }
}
