import 'package:flutter/material.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensinotifwidget/generated/GeneratedWorking1Widget.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensinotifwidget/generated/GeneratedSelamatbekerjaTheNormalWaygunakanselalumaskerselamadika.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensinotifwidget/generated/GeneratedBrianMayMilwaukeeWidget2.dart';
import 'package:flutterapp/pelni_oneapp/generatedpelniabsensinotifwidget/generated/GeneratedSelamatDatangWidget.dart';

/* Frame Pelni Absensi Notif
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPelniAbsensiNotifWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedPelniAbsensiWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(10.0),
        child: Container(
          width: 375.0,
          height: 442.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(10.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(10.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 107.0,
                  top: 38.0,
                  right: null,
                  bottom: null,
                  width: 163.0,
                  height: 22.0,
                  child: GeneratedSelamatDatangWidget(),
                ),
                Positioned(
                  left: 91.0,
                  top: 70.0,
                  right: null,
                  bottom: null,
                  width: 196.0,
                  height: 22.0,
                  child: GeneratedBrianMayMilwaukeeWidget2(),
                ),
                Positioned(
                  left: 11.0,
                  top: 100.0,
                  right: null,
                  bottom: null,
                  width: 355.0,
                  height: 82.0,
                  child:
                      GeneratedSelamatbekerjaTheNormalWaygunakanselalumaskerselamadika(),
                ),
                Positioned(
                  left: -36.0,
                  top: 186.0,
                  right: null,
                  bottom: null,
                  width: 448.0,
                  height: 224.0,
                  child: GeneratedWorking1Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
